name: Python Linting and Formatting

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - pyrightconfig.json
      - ruff.toml
      - .github/workflows/workflows.yml
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - pyrightconfig.json
      - ruff.toml
      - .github/workflows/workflows.yml

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          pip install pyright ruff
          pip install -r requirements.txt

      - name: Type checking
        run: pyright

      - name: Linting
        run: ruff check .
